all-changed:
  - "**"
components:
  - "elements/**/src/*"
demo:
  - "elements/**/demo/*"
  - "examples/*"
tests:
  - "elements/**/test/*"
  - "test/**"
  - "scripts/test-suite-inject.js"
  - "scripts/test.{js,sh}"
build-tools:
  - "scripts/{build,dev}.sh"
  - "scripts/gulpfile.factory.js"
  - "scripts/rollup.config.factory.js"
repo-tools:
  - "generators/**"
  - ".github/workflows/**"
  - ".github/*.yml"
  - "scripts/**"
  - "!scripts/{build,dev}.sh"
  - "!scripts/test.{js,sh}"
  - "!scripts/gulpfile.factory.js"
  - "!scripts/rollup.config.factory.js"
docs:
  - "docs/**"
  - "brand/**"
  - ".storybook/**"
  - "**/*.{md,text}"
no-at:
  - "**"
  - "!.github/ISSUE_TEMPLATE/**"
  - "!.github/PULL_REQUEST_TEMPLATE/**"
  - "!.storybook/**"
  - "!**/*.{md,text}"
