all-changed:
  - "**"
components: &components
  - added|modified: "elements/**/src/*"
new_component:
  - added: "elements/*"
demo:
  - "elements/**/demo/*"
  - "examples/*"
tests: &tests
  - "elements/**/test/*"
  - "test/**"
  - "scripts/test-suite-inject.js"
  - "scripts/test.{js,sh}"
  - "wct.conf.json"
  - "wdio.conf.js"
build-tools: &scripts
  - "scripts/{build,dev}.sh"
  - "scripts/gulpfile.factory.js"
  - "scripts/rollup.config.factory.js"
  - "package.json"
repo-tools:
  - "generators/**"
  - ".github/workflows/**"
  - ".github/*.yml"
  - "scripts/**"
  - "!scripts/{build,dev}.sh"
  - "!scripts/test.{js,sh}"
  - "!scripts/gulpfile.factory.js"
  - "!scripts/rollup.config.factory.js"
# docs:
#   - "docs/**"
#   - "brand/**"
#   - ".storybook/**"
#   - "**/*.{md,text}"
run-at:
  - *scripts
  - *components
  - added|modified: *tests
