# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To view the configuration, go to: .github/labeler.yml
name: Auto-label PRs

on:
  pull_request:
    types:
      - opened
      - convert_to_draft
      - ready_for_review
  pull_request_review:
    types:
      - submitted

env:
  TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

# Separate jobs can run concurrently
jobs:
  triage:
    name: Apply triage labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ env.TOKEN }}

  mergeable:
    name: Flag a PR ready to merge
    runs-on: ubuntu-latest

    steps:
      - name: Flag work in progress
        if: github.event.pull_request.draft
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: work in progress

      - name: Flag ready to merge
        # Add a ready to merge label if the PR is approved and the test suite has passed
        if: |
          (
            github.event_name == 'pull_request' &&
            !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
            !contains(github.event.pull_request.labels.*.name, 'on hold') &&
            !contains(github.event.pull_request.labels.*.name, 'blocked') &&
            !contains(github.event.pull_request.labels.*.name, 'skip vrt') &&
            !contains(github.event.pull_request.labels.*.name, 'needs:*') && (
              contains(github.event.pull_request.labels.*.name, 'ready to merge') ||
              contains(github.event.pull_request.user.login, 'dependabot') ||
              contains(github.event.pull_request.user.login, 'dependabot-preview')
            )
          ) || (
            github.event_name == 'pull_request_review' &&
            github.event.review.state == 'approved'
          )
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: ready to merge

      - name: Remove label if approval dismissed
        # Add a ready to merge label if the PR is approved and the test suite has passed
        if: github.event_name == 'pull_request_review' && github.event.review.state != 'approved'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: ready to merge
