# This workflow will automatically move cards
# in the project board to reflect that status
# of an issue or PR.
name: Move card in project view when label updated
on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PROJECT_URL: https://github.com/orgs/github/projects/2
jobs:
  project_board:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.*.state) }}
          GITHUB_LABELS: ${{ toJson(github.event.*.labels.*.name) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_LABELS"
      # - uses: takanabe/github-actions-automate-projects@v0.0.1
      #   if: |
      #     (
      #       github.event_name == 'issues' &&
      #       github.event.issue.state == 'open' &&
      #       contains(github.event.issue.labels.*.name, 'discovery')
      #     ) || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.state == 'open' &&
      #       contains(github.event.pull_request.labels.*.name, 'discovery')
      #     )
      #   env:
      #     GITHUB_PROJECT_COLUMN_NAME: Backlog
      # - uses: takanabe/github-actions-automate-projects@v0.0.1
      #   if: |
      #     contains(github.event.*.state, 'open') &&
      #     (
      #       contains(github.event.issue.labels.*.name, 'blocked') ||
      #       contains(github.event.issue.labels.*.name, 'on hold')
      #     )
      #   env:
      #     GITHUB_PROJECT_COLUMN_NAME: On hold
      # - uses: takanabe/github-actions-automate-projects@v0.0.1
      #   if: |
      #     (
      #       github.event_name == 'issues' &&
      #       github.event.issue.state == 'open'
      #       && contains(github.event.issue.labels.*.name, 'needs: code review')
      #     ) || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.state == 'open'
      #       && contains(github.event.pull_request.labels.*.name, 'needs: code review')
      #     )
      #   env:
      #     GITHUB_PROJECT_COLUMN_NAME: Code review
      # - uses: takanabe/github-actions-automate-projects@v0.0.1
      #   if: |
      #     (
      #       github.event_name == 'issues' &&
      #       github.event.issue.state == 'open' &&
      #       contains(github.event.issue.labels.*.name, 'testing')
      #     ) || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.state == 'open' &&
      #       (
      #         contains(github.event.pull_request.labels.*.name, 'needs: browser testing') ||
      #         contains(github.event.pull_request.labels.*.name, 'needs: branch testing')
      #       )
      #     )
      #   env:
      #     GITHUB_PROJECT_COLUMN_NAME: Testing
      # - uses: takanabe/github-actions-automate-projects@v0.0.1
      #   if: |
      #     (
      #       github.event_name == 'issues' &&
      #       github.event.issue.state == 'open'
      #       && contains(github.event.issue.labels.*.name, 'ready for merge')
      #     ) || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.state == 'open' &&
      #       contains(github.event.pull_request.labels.*.name, 'ready for merge')
      #     )
      #   env:
      #     GITHUB_PROJECT_COLUMN_NAME: Ready for merge?
