# This workflow will build and run the test suite
# on all opened and updated (and labeled) PRs where
# at least one file does not match paths-ignore.
name: Build & test

on:
  # Build when a PR
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - ready_for_review
    # Will only run if files other than these are edited
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE/**"
      - ".storybook/**"
      - "docs/**"
      - "generators/**"
      - "**/*.md"
      - "**/*.text"
      - "*.md"
  # Build when PRs are merged into master/main
  push:
    branches: [master, main]
  # Manual run, no inputs necessary
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # For webdriver script
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

  # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

  # Turn this on to debug an action
  # GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  check:
    name: Check labels
    outputs:
      SKIP_VRT: ${{ steps.skip_vrt.outcome == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for the skip vrt label
        if: |
          ( github.event_name == 'labeled' && github.event.label.name == 'skip vrt') ||
          ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name , 'skip vrt'))
        id: skip_vrt
        run: echo "Skip visual regression testing due to the 'skip vrt' label being present"

  # E2E command can run concurrent with test so it downloads the
  # compiled assets from the build and uses those instead of reinstalling.
  # Only run visual tests if the PR is labeled "ready to merge" or "run e2e"
  vrt:
    name: Visual regression testing
    needs: [check]
    if: needs.check.outputs.SKIP_VRT == false
    # if: |
    #   contains(github.event.pull_request.labels.*.name, 'ready to merge') ||
    #   contains(github.event.pull_request.labels.*.name, 'run e2e') ||
    #   contains(github.event.pull_request.user.login, 'dependabot') ||
    #   contains(github.event.pull_request.user.login, 'dependabot-preview')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - name: Testing skip label
        run: echo "Skip visual regression testing due to the 'skip vrt' label being present"
