# This workflow will build and run the test suite
# on all opened and updated (and labeled) PRs where
# at least one file does not match paths-ignore.
name: Build & test

on:
  # Build when a PR
  pull_request:
    types:
      - labeled
      - ready_for_review
      - opened
      - synchronize
    # Will only run if files other than these are edited
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE/**"
      - ".storybook/**"
      - "docs/**"
      - "generators/**"
      - "**/*.md"
      - "**/*.text"
      - "*.md"
  # Build when PRs are merged into master/main
  push:
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # For webdriver script
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

  # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

  # Turn this on to debug an action
  # GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  check:
    name: Validate if tests should be run
    outputs:
      RUN_TESTS: ${{ steps.run_tests.outcome != 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      # Checks if all tests should be run on this event
      - name: Check if any tests should be run on this event
        if: |
          github.event_name == 'push' || (
            github.event_name == 'pull_request' &&
            github.event.pull_request.draft == 'false' && 
            !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
            !contains(github.event.pull_request.labels.*.name, 'on hold') &&
            !contains(github.event.pull_request.labels.*.name, 'blocked') &&
            !contains(github.event.pull_request.labels.*.name, 'skip vrt') &&
            !contains(github.event.pull_request.labels.*.name, 'needs:*') && (
              contains(github.event.pull_request.labels.*.name, 'ready to merge') ||
              contains(github.event.pull_request.labels.*.name, 'run vrt') ||
              contains(github.event.pull_request.user.login, 'dependabot') ||
              contains(github.event.pull_request.user.login, 'dependabot-preview')
            )
          )
        id: run_tests
        run: exit 0

  build:
    name: Compile project
    needs: check
    outputs:
      CACHE_KEY: ${{ steps.hash.outputs.HASH }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    if: needs.check.outputs.RUN_TESTS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Capture hash value
        id: hash
        run: echo '::set-output name=HASH::${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}'

      # Configures the node version used on GitHub-hosted runners
      - name: Configure node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Caching speeds up the npm install step
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ steps.hash.outputs.HASH }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        id: build
        run: npm run build

      # Upload compiled assets to make them available for downstream jobs
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-assets
          path: elements/*/dist/*
          if-no-files-found: error

  # Test command can run concurrent with e2e so it downloads the
  # compiled assets from the build and uses those instead of reinstalling.
  test:
    name: Run test suite (wct)
    needs: [check, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configures the node version used on GitHub-hosted runners
      - name: Configure node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Caching speeds up the npm install step
      - name: Access cached node modules
        id: get-node-cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ needs.build.outputs.CACHE_KEY }}

      - name: Install dependencies
        if: steps.get-node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Access compiled assets
        uses: actions/download-artifact@v2
        id: download-compiled-assets
        with:
          name: compiled-assets
          path: elements

      - name: Build
        if: failure()
        run: npm run build

      - name: Run tests
        run: npm test -- --build=false --verbose
