# This workflow will build and run the test suite
# on all opened and updated (and labeled) PRs where
# at least one file does not match paths-ignore.
name: Build & test

on:
  # Build when a PR
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - ready_for_review
    # Will only run if files other than these are edited
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE/**"
      - ".storybook/**"
      - "docs/**"
      - "generators/**"
      - "**/*.md"
      - "**/*.text"
      - "*.md"
  # Build when PRs are merged into master/main
  push:
    branches: [master, main]
  # Manual run, no inputs necessary
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # For webdriver script
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

  # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

  # Turn this on to debug an action
  # GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  check:
    name: Check labels
    outputs:
      RUN_TESTS: ${{ steps.run_tests.outcome != 'skipped' }}
      SKIP_VRT: ${{ steps.skip_vrt.outcome == 'skipped' }}
      RUN_VRT: ${{ steps.run_vrt.outcome != 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      # Checks if all tests should be run on this event
      # - name: Check if any tests should be run on this event
      #   if: |
      #     github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (
      #       github.event_name == 'pull_request' &&
      #       github.event.pull_request.draft == false &&
      #       !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
      #       !contains(github.event.pull_request.labels.*.name, 'on hold')
      #     )
      #   id: run_tests
      #   run: exit 0

      # Skipping visual regression tests means no VRT should be run at all before merging
      - name: Check if vrt should be skipped for this PR
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip vrt')
        id: skip_vrt
        run: exit 0

      # Checks if the visual regression tests should be run on this event
      - name: Check if vrt should be run on this event
        if: |
          github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (
            github.event_name == 'pull_request' && 
            github.event.pull_request.draft == false && (
              contains(github.event.pull_request.labels.*.name, 'ready to merge') ||
              contains(github.event.pull_request.labels.*.name, 'run e2e') ||
              contains(github.event.pull_request.labels.*.name, 'run vrt') ||
              contains(github.event.pull_request.user.login, 'dependabot') ||
              contains(github.event.pull_request.user.login, 'dependabot-preview')
            )
          )
        id: run_vrt
        run: exit 0

  test:
    name: Test checks
    needs: [check]
    if: ${{ needs.check.outputs.RUN_VRT == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      # Set this step to pass if we have set this PR to skip VRT entirely
      - name: Pass step if skip vrt is present
        if: ${{ needs.check.outputs.SKIP_VRT == 'true' }}
        run: exit 0
