name: Visual regression testing
on:
  workflow_dispatch:
    inputs:
      components:
        description: "Component(s) to test [space-separated] (optional)"
        required: false
  pull_request:
    types: [labeled]
    paths:
      - "elements"
      - "scripts"
jobs:
  visual_regression_tests:
    if: true || contains(github.event.pull_request.labels.*.name, 'ready to merge')  || contains(github.event.pull_request.labels.*.name, 'run e2e')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Echo
        run: echo ${{ github.event.type }}

      - name: BrowserStackLocal env setup
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USER }}
          access-key: ${{ secrets.BROWSERSTACK_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Start BrowserStackLocal
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: start
          local-identifier: random
          # local-logging-level: all-logs

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Visual regression tests
        run: npm run e2e -- ${{ github.event.inputs.components }} --verbose

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: baseline-comparisons
          path: |
            ./test/vrt-compare/

      - name: Stop BrowserStackLocal
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: stop
